### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by mlynekg** [yo5ptd/HeapumpWeb#1]
Hello
Congratulations on the idea.
I have a request if you would help me develop this project
for reading data from a Samsung ehs heat pump
your code reads fan orots, compressor current, gas temperature and outside temperature.
How to read the inlet and outlet water temperature on the hydrobox unit exchanger and the temperature in the domestic hot water tank?

Regards

**Comment by yo5ptd** [comment]
Sorry for the late reply @mlynekg . It's been too long, I don't remember other readings, and the piece of paper where I made my notes is long lost.

I recommend looking into https://github.com/DannyDeGaspari/Samsung-HVAC-buscontrol ,  sniffing the communication on RS485 seems like a good start if find what are you looking for by using Jetbrains dotPeek on "SNET Pro Service Software (non NASA)" from Samsung.

You can read the value from the Hidrobox, and compare it to the sniffed data. If you find them, would be nice to have a pull request from you.
