### ISSUE TITLE
Thank you! this is amazing! 

### ISSUE THREAD

**Issue by wofforduk** [yo5ptd/HeapumpWeb#2]
Is there any more data that can be read or set? Ideally I would like to control DHW from rpi to make use of cheaper electricity

**Comment by yo5ptd** [comment]
Sorry for the late answer @wofforduk. 

Please download and install https://s3.amazonaws.com/samsung-files/Tech_Files/SNET+Pro+and+SNET+Pro+2+Service+Software/Snet+Pro+v1.5.3.zip or search for "SNET Pro Service Software (Non-NASA Systems)" if the link goes down.
 
You can test the service software if it can set the DHW temp, and if it can, then install Jetbrains DotPeek explore the folder you have installed SNET Pro from above, **everything** can be decompiled. 

RPI can run .net core, so you have all the .net code needed from the decompiled sources.

Let me know if there is anything else I can help you with.

**Comment by yo5ptd** [comment]
In the meantime I've remembered, the commands are for the external unit only made by Samsung, so no idea about the commands to control the internal hydro unit.
Easiest would be a timer that cuts off the external probe from the DWH tank. It will give you E12 during the off period.  If bothers you, but you can experiment with a fixed sized resistor  (telling the unit the water in the tank is hot) and switch between the resistor and actual probe.
